name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: publish
        run: |
          git config --global user.name 'Betty Grof'
          git config --global user.email 'subpark1219@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/parksb/papers-i-love
          git switch gh-pages
          git pull origin main --rebase
          cd scripts
          npm install
          npm run build
          git add -A
          git commit -m "dist: $(date)"
          git pull origin gh-pages --rebase
          git push origin gh-pages
